import type { JobApplication, ResumeFile } from "../types/application";

export const mockResumes: ResumeFile[] = [
  {
    id: "resume-frontend",
    displayName: "Frontend Internship Resume",
    originalFileName: "frontend-internship-resume.pdf",
    fileExtension: "pdf",
    uploadedAt: "2026-08-15",
    lastUsedAt: "2026-08-29",
  },
  {
    id: "resume-product",
    displayName: "Product Engineering Resume",
    originalFileName: "product-engineering-resume.docx",
    fileExtension: "docx",
    uploadedAt: "2026-08-20",
    lastUsedAt: "2026-09-01",
  },
];

export const mockApplications: JobApplication[] = [
  {
    id: "app-01",
    company: "Northstar Labs",
    jobTitle: "Frontend Engineering Intern",
    jobDescription:
      "Build polished React interfaces for internal data tools, collaborate with design on reusable components, and improve loading states across the internship platform.",
    status: "Pending Interview - Technical",
    location: "Singapore",
    workMode: "hybrid",
    jobType: "internship",
    source: "LinkedIn",
    applicationUrl: "https://example.com/northstar",
    dateFound: "2026-08-19",
    dateApplied: "2026-08-22",
    deadline: "2026-09-12",
    followUpNeeded: true,
    followUpDate: "2026-09-05",
    interviewDateTime: "2026-09-08T10:30:00+08:00",
    interviewType: "technical",
    interviewMode: "video",
    interviewPlatform: "Zoom",
    interviewProctored: false,
    deadlineEntryMode: "exact",
    nextAction: "Review React performance notes",
    priority: "high",
    resumeId: "resume-frontend",
    contactsCount: 2,
    updatedAt: "2026-09-02T17:30:00+08:00",
    createdAt: "2026-08-22T21:10:00+08:00",
  },
  {
    id: "app-02",
    company: "Atlas Fintech",
    jobTitle: "Software Engineer Intern",
    jobDescription:
      "Join a platform squad building transaction monitoring workflows, writing TypeScript services, and pairing with senior engineers on reliability improvements.",
    status: "Awaiting Response",
    location: "Remote",
    workMode: "remote",
    jobType: "internship",
    source: "Referral",
    applicationUrl: "https://example.com/atlas",
    dateFound: "2026-08-24",
    dateApplied: "2026-08-25",
    deadline: "2026-09-15",
    deadlineEntryMode: "exact",
    followUpNeeded: true,
    followUpDate: "2026-09-01",
    interviewProctored: false,
    nextAction: "Send polite follow-up",
    priority: "medium",
    resumeId: "resume-product",
    contactsCount: 1,
    updatedAt: "2026-09-01T09:15:00+08:00",
    createdAt: "2026-08-25T20:20:00+08:00",
  },
  {
    id: "app-03",
    company: "Helio Systems",
    jobTitle: "Full Stack Developer Intern",
    jobDescription:
      "Work on customer-facing dashboard features, improve API integration tests, and document backend handoff points for a small product engineering team.",
    status: "Applied",
    location: "Singapore",
    workMode: "onsite",
    jobType: "internship",
    source: "Company site",
    applicationUrl: "https://example.com/helio",
    dateFound: "2026-08-30",
    dateApplied: "2026-09-01",
    deadline: "2026-09-20",
    deadlineEntryMode: "exact",
    followUpNeeded: false,
    followUpDate: "2026-09-08",
    interviewProctored: false,
    nextAction: "Wait for response",
    priority: "low",
    resumeId: "resume-frontend",
    contactsCount: 0,
    updatedAt: "2026-09-01T22:45:00+08:00",
    createdAt: "2026-09-01T22:45:00+08:00",
  },
  {
    id: "app-04",
    company: "Mosaic AI",
    jobTitle: "Product Engineering Intern",
    jobDescription:
      "Prototype AI-assisted workflows, translate ambiguous user needs into small experiments, and ship UI improvements with careful event instrumentation.",
    status: "Offered",
    location: "Singapore",
    workMode: "hybrid",
    jobType: "internship",
    source: "Career fair",
    dateFound: "2026-08-03",
    dateApplied: "2026-08-05",
    deadline: "2026-08-28",
    roleStartDate: "2027-01-12",
    roleEndDate: "2027-05-30",
    followUpNeeded: false,
    interviewDateTime: "2026-08-26T14:00:00+08:00",
    interviewType: "face-to-face",
    interviewMode: "onsite",
    interviewLocation: "Singapore office",
    interviewProctored: false,
    deadlineEntryMode: "exact",
    nextAction: "Compare offer details",
    priority: "high",
    resumeId: "resume-product",
    contactsCount: 3,
    updatedAt: "2026-08-30T12:10:00+08:00",
    createdAt: "2026-08-05T18:05:00+08:00",
  },
  {
    id: "app-05",
    company: "Pinnacle Cloud",
    jobTitle: "Cloud Platform Intern",
    jobDescription:
      "Support internal tooling for deployment visibility, handle small bug fixes in React and Go, and prepare concise runbooks for common operations.",
    status: "Rejected",
    location: "Singapore",
    workMode: "hybrid",
    jobType: "internship",
    source: "School portal",
    dateFound: "2026-08-10",
    dateApplied: "2026-08-11",
    deadline: "2026-08-25",
    deadlineEntryMode: "exact",
    followUpNeeded: false,
    interviewProctored: false,
    nextAction: "Archive after review",
    priority: "medium",
    resumeId: "resume-frontend",
    contactsCount: 1,
    updatedAt: "2026-08-28T16:00:00+08:00",
    createdAt: "2026-08-11T13:40:00+08:00",
  },
  {
    id: "app-06",
    company: "CircuitWorks",
    jobTitle: "QA Automation Intern",
    jobDescription:
      "Create browser regression checks for application flows, triage defects with product managers, and strengthen test coverage around release-critical paths.",
    status: "Pending Interview - HireVue",
    location: "Remote",
    workMode: "remote",
    jobType: "internship",
    source: "LinkedIn",
    dateFound: "2026-08-27",
    dateApplied: "2026-08-29",
    deadline: "2026-09-10",
    followUpNeeded: true,
    followUpDate: "2026-09-07",
    interviewDateTime: "2026-09-06T23:59:00+08:00",
    interviewType: "HireVue",
    interviewMode: "video",
    interviewPlatform: "HireVue",
    interviewProctored: true,
    deadlineEntryMode: "exact",
    nextAction: "Record HireVue answers",
    priority: "medium",
    contactsCount: 0,
    updatedAt: "2026-09-02T08:25:00+08:00",
    createdAt: "2026-08-29T11:50:00+08:00",
  },
];
